Add minimize to tray support.
DiscordMessenger/dm pull request #113
Opened 2024-06-26 19:26 UTC by KnockKnockP

2024-06-26 21:00 UTC, iProgramMC commented
Thanks!  I'll take a look.

On Wed, Jun 26, 2024, 22:26 KnockKnockP ***@***.***> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/DiscordMessenger/dm/pull/113
> Commit Summary
>
>    - 90c062f
>    <https://github.com/DiscordMessenger/dm/pull/113/commits/90c062fd579b54b2a74d7d7e8d7f8f9cf2449be6>
>    Add minimize to tray support.
>    - 8ebae27
>    <https://github.com/DiscordMessenger/dm/pull/113/commits/8ebae27311c20528b43ca3cd0d7977aea64eb6c3>
>    Fix formatting.
>    - 0465176
>    <https://github.com/DiscordMessenger/dm/pull/113/commits/046517631325fb79cc066e4b1d438bca7c33fa8d>
>    Check for an existing instance.
>
> File Changes
>
> (10 files <https://github.com/DiscordMessenger/dm/pull/113/files>)
>
>    - *M* src/discord/Frontend.hpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-2650ebab60bec0a17ef17354afdc8d4cf9237ede6fef46d5f7c27be8eccd42eb>
>    (3)
>    - *M* src/discord/LocalSettings.cpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-bbf1e5699754196d06bca3174752ab5d618b447fbdcc79b319ec0674600c68ad>
>    (3)
>    - *M* src/discord/LocalSettings.hpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-a1391d015c1c2d5796fc98f6d7d9b772aa0a653a599142e606ac9a6ae924b936>
>    (7)
>    - *M* src/resource.rc
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-cc577575527473f3c070b71593de5f79b85106e337dae49a1f5be09c603bc94c>
>    (2)
>    - *M* src/windows/Frontend_Win32.cpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-419c7af5bbab0d55947c354dd24e5bfd9ea67ff571cfdc7a162835bbeb7d718a>
>    (10)
>    - *M* src/windows/Frontend_Win32.hpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-5a3396ef36bafd748fa69aad0a6c3a72b172d0da550bd582815660c182d69d32>
>    (2)
>    - *M* src/windows/Main.cpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-ac245fba55fd93b676b619ff3379d0181aade961dd2dad760540a6f5c24d9102>
>    (63)
>    - *M* src/windows/OptionsDialog.cpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-898c35eeaa52310d18c12103c20166f833d3998e22fd468832cbc1aa686ab08d>
>    (8)
>    - *M* src/windows/ShellNotification.cpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-ab013b06711afb29839afc82f992e71d43df4d555c7d2b3c038e15f9977bc96f>
>    (23)
>    - *M* src/windows/ShellNotification.hpp
>    <https://github.com/DiscordMessenger/dm/pull/113/files#diff-7dddef4a34a4eaec77aae100c0857f8592ece1844c8c6790a984eda8600d6086>
>    (1)
>
> Patch Links:
>
>    - https://github.com/DiscordMessenger/dm/pull/113.patch
>    - https://github.com/DiscordMessenger/dm/pull/113.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DiscordMessenger/dm/pull/113>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEHFR5RXBOXX6RLDEHBKB63ZJMIXBAVCNFSM6AAAAABJ6QMC4GVHI2DSMVQWIX3LMV43ASLTON2WKOZSGM3TMMJQHA3TANY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-06-27 02:27 UTC, KnockKnockP commented
Thinking about it, I could probably just use mutex to force single instance. I don't know why I overcomplicated it.

2024-06-27 08:17 UTC, iProgramMC commented
Yeah, you can do that. Here's an example:
```cpp

// I use a class here to perform cleanup after winmain
class InstanceMutex
{
	HANDLE m_handle = NULL;

public:
	HRESULT Init()
	{
#ifdef _DEBUG
		return 0;
#else
		SetLastError(NO_ERROR);

		m_handle = CreateMutex(NULL, TRUE, WINDOW_CLASS);

		if (GetLastError() == ERROR_ALREADY_EXISTS)
		{
			if (m_handle)
			{
				CloseHandle(m_handle);
				m_handle = NULL;
			}

			return ERROR_ALREADY_EXISTS;
		}

		return GetLastError();
#endif
	}

	~InstanceMutex()
	{
#ifdef _DEBUG
		if (m_handle)
			CloseHandle(m_handle);
#endif
	}
};

InstanceMutex g_instanceMutex;

bool DetectDuplicateInstances()
{
    HRESULT hres = g_instanceMutex.Init();
    if (hres != ERROR_ALREADY_EXISTS) return false;
    
    HWND hWnd = FindWindow(WINDOW_CLASS_NAME, NULL);
    if (hWnd) {
        SendMessage (hWnd, WM_REQUESTACTIVATE, 0, 0);
        return true;
    }
    
    return false;
}
```

2024-06-27 09:41 UTC, iProgramMC requested changes

2024-06-27 09:41 UTC, iProgramMC commented on src/windows/InstanceMutex.cpp
> +	m_handle = CreateMutex(NULL, TRUE, L"DiscordMessenger");
Use `TEXT()`.

2024-06-27 09:41 UTC, iProgramMC commented on src/windows/InstanceMutex.cpp
> +	if (error == ERROR_ALREADY_EXISTS)
Check for the presence of `m_handle` instead of resetting the last error status.

2024-06-27 09:41 UTC, iProgramMC commented on src/windows/Main.cpp
> +	return true;
Return `false` here, and return `true` after the `SendMessage` call.

2024-06-27 09:42 UTC, iProgramMC requested changes

2024-06-27 09:42 UTC, iProgramMC commented on src/windows/Main.cpp
> +			if (GetLocalSettings()->GetMinimizeToNotif())
There's a separate setting called "Start minimized", add that and use it here

2024-06-27 09:42 UTC, iProgramMC commented on src/windows/ShellNotification.cpp
> +	InsertMenu(popupMenu, 0, MF_BYPOSITION | MF_STRING, WM_DESTROY, L"Exit");
Use `TEXT()`.

2024-06-29 18:22 UTC, iProgramMC requested changes

2024-06-29 18:22 UTC, iProgramMC commented on src/windows/Main.cpp
> +			if (GetLocalSettings()->GetStartMaximized())
Add the option to start minimized.

2024-06-29 18:22 UTC, iProgramMC commented on src/windows/Main.cpp
>  	}
Return `false` in the condition, and `true` just below.

2024-06-29 18:25 UTC, iProgramMC requested changes

2024-06-29 18:25 UTC, iProgramMC commented on src/discord/LocalSettings.hpp
> +	bool GetStartMinimized() const {
Call these `OpenOnStartup()` and `StartMinimized()`.

2024-06-29 18:29 UTC, iProgramMC commented on src/windows/Main.cpp
> +					GetLocalSettings()->SetMaximized(true);
can just do `GetLocalSettings()->SetMaximized (wParam == SIZE_MAXIMIZED);`

2024-06-29 18:29 UTC, iProgramMC commented on src/windows/WindowMessages.hpp
> +	WM_RESTORE,
May want to call it something like `WM_RESTOREAPP`, because more than once did I confuse this for an actual Windows window message

2024-06-29 18:29 UTC, iProgramMC commented on src/discord/LocalSettings.cpp
> +		m_bMinimizeToNotif = j["m_bMaximized"];
Use `Maximized` in the JSON key.

2024-06-29 19:07 UTC, KnockKnockP commented on src/discord/LocalSettings.cpp
> +		m_bMinimizeToNotif = j["m_bMaximized"];
This is embarrassing.

2024-06-30 10:30 UTC, iProgramMC approved these changes
Looks good to me :)

2024-06-30 10:30 UTC, iProgramMC commented on src/windows/Main.cpp
> +		const std::string sPath = "\"" + MakeStringFromTString(tPath) + "\"" + MakeStringFromTString(g_tStartupArg);
Change `MakeStringFromTString(g_tStartupArg)` with `std::string (g_StartupArg)`

2024-07-20 08:54 UTC, merged